### ISSUE TITLE
Improve English language string mod_surveypro mastertemplate_help

### ISSUE THREAD

**Issue by germanvaleroelizondo** [kordan/moodle-mod_surveypro#282]
Hi,
One suggestion for one English language string: **mod_surveypro mastertemplate_help**
'Choose the master template you want to apply to your survey.'

This help string does not help much :(

Maybe it would help more if it actually described the available survey types; e.g.

'Choose the master template you want to apply to your survey. The available types are:
- ATTLS. ''Attitudes to Thinking and Learning Survey''. See https://docs.moodle.org/31/en/Survey_settings#ATTLS_-_Attitudes_to_Thinking_and_Learning_Survey.
- COLLES. ''Constructivist On-Line Learning Environment Survey''. See https://docs.moodle.org/31/en/Survey_settings#COLLES_-_Constructivist_On-Line_Learning_Environment_Survey.
- CRITICAL INCIDENTS. See https://docs.moodle.org/31/en/Survey_settings#Critical_incidents.'

The links to the current documentation pages might be written as 'More information...' or a similar text.

Thanks in advance for your help improving this already great plugin.

**Comment by kordan** [comment]
Ciao German, I agree with you about the improvement but please file a standard pull request by:
- cloning the repo
- adding a new branch
- make the modification
- push the Peer review here.
Once I get the request, I will probably agree and merge.

**Comment by germanvaleroelizondo** [comment]
Ciao,

I will, but it may take me some time. 
I am not a programmer, I am a veterinarian. 
I have never filed a standard pull request.
I will try to make time this coming weekend.

Yours sincerely,

**Comment by germanvaleroelizondo** [comment]
I first need how to make an English language string that will show as 'more help...' and link to the mentioned Moodle Docs page. I will look at the existing strings and copy the syntax.

Maybe I need to install Git on my PC in order to clone the repo and add a new branch in my desktop and make there the modifications before pushing the peer review at GitHub. 

I will continue on saturday at home with a big PC...

**Comment by kordan** [comment]
Git is not simple at first. Sometimes I have problems with it. However the basic use that we are supposed to make is really simple. There are also some free software like the ones described [here] (https://git-scm.com/download/gui/linux) providing GUI tools for committing.

**Comment by germanvaleroelizondo** [comment]
I found an example of the syntax I want (I think).

The original string is 
$string['mastertemplate_help'] = 'Choose the master template you want to apply to your survey.';

My (very long) suggested string will be 
$string['mastertemplate_help'] = ''Choose the master template you want to apply to your survey. The available types are:

    ATTLS. ''Attitudes to Thinking and Learning Survey''. For more details, see the documentation <a href="https://docs.moodle.org/31/en/Survey_settings#ATTLS_-_Attitudes_to_Thinking_and_Learning_Survey">ATTLS explained</a>.

    COLLES. ''Constructivist On-Line Learning Environment Survey''. For more details, see the documentation <a href="https://docs.moodle.org/31/en/Survey_settings#COLLES_-_Constructivist_On-Line_Learning_Environment_Survey">COLLES explained</a>.

    CRITICAL INCIDENTS. For more details, see the documentation <a href="https://docs.moodle.org/31/en/Survey_settings#Critical_incidents.'">Critical incidents explained</a>;

NOW I only need to learn to use GitHub commits... 

TOMORROW will be Saturday and I will have more time. 
I think I am learning; therefore, I am happy...

**Comment by germanvaleroelizondo** [comment]
![mastertemplate_help](https://cloud.githubusercontent.com/assets/2671923/19391929/3cc63806-91f4-11e6-944b-08619589cfe1.png)

It seems to be fine in my local server. I am happy...

**Comment by kordan** [comment]
take care because surveypro can GENERATE new master templates from each surveypro you build manually. Once the mastertemplate is generated it can be downloaded and installed. This to allow the multilanguage surveypro.

All this story to tell you that each list in $string['mastertemplate_help'] is always a partial list so... maybe you can start the  string with "Choose a master template like one of the ones provided by default or a custom one you added to this instance of surveypro". This is only a suggestion. Not an imposition at all. Only for your information.
Ciao and have a nice week end,

**Comment by germanvaleroelizondo** [comment]
I will build a couple of surveypro activities in my local server and see how it goes. I  will report later.

**Comment by germanvaleroelizondo** [comment]
And how would this look to you?:
![surveypro mastertemplate_help string proposal](https://cloud.githubusercontent.com/assets/2671923/19503012/64dfff5e-9576-11e6-95a2-24fe177297d3.png)

**Comment by germanvaleroelizondo** [comment]
Is this new proposed help string more helpful?

**Comment by kordan** [comment]
Cool. Thanks. Send me, please, the string. I will open an issue, I will fix it and I will send for integration.

**Comment by germanvaleroelizondo** [comment]
You can copy the string from here:

My (very long) (twice changed, improved) suggested string will be:

$string['mastertemplate_help'] = 'Choose a master template like one of the classical ones provided by default or a custom one you added to this instance of surveypro. The classical survey types are:

ATTLS. ''Attitudes To Thinking and Learning Survey''. For more details, see the documentation on <a href="https://docs.moodle.org/31/en/Survey_settings#ATTLS_-_Attitudes_to_Thinking_and_Learning_Survey">ATTLS</a>.

COLLES. ''Constructivist On-Line Learning Environment Survey''. For more details, see the documentation on <a href="https://docs.moodle.org/31/en/Survey_settings#COLLES_-_Constructivist_On-Line_Learning_Environment_Survey">COLLES</a>.

CRITICAL INCIDENTS. For more details, see the documentation on <a href="https://docs.moodle.org/31/en/Survey_settings#Critical_incidents">Critical incidents</a>';



I promise I will study Git and soon I might even be able to make a pull request...

**Comment by germanvaleroelizondo** [comment]
![mastertemplate_help_code](https://cloud.githubusercontent.com/assets/2671923/19522985/bc1fe1a4-95de-11e6-88b5-82cfe60ce48b.png)

**Comment by kordan** [comment]
Added a PR in https://github.com/kordan/moodle-mod_surveypro/pull/291

**Comment by stronk7** [comment]
Note that, with #291 already merged, surely this can be considered done and close it. Thanks!

**Comment by kordan** [comment]
Closing as fixed in the frame of https://github.com/kordan/moodle-mod_surveypro/pull/291.
Thanks a lot!
