### ISSUE TITLE
Fix tiny typo in English language string surveyprofield_checkbox 	adjustment_help

### ISSUE THREAD

**Issue by germanvaleroelizondo** [kordan/moodle-mod_surveypro#283]
Please fix: 
surveyprofield_checkbox 	adjustment_help
	
'How this list of items will be shown? In horital or in vertical?'

'horital' should be 'horizontal'

**Comment by kordan** [comment]
Please file a regular pull request as I did for this issue.
Look at: https://github.com/kordan/moodle-mod_surveypro/pull/284
Thanks a lot.

**Comment by germanvaleroelizondo** [comment]
I will, as soon as I learn how to do that.

**Comment by kordan** [comment]
it is simpler than expected and, for sure, all is well documented in moodle forums.

**Comment by kordan** [comment]
Fixed in https://github.com/kordan/moodle-mod_surveypro/pull/284.
Thanks.
