### ISSUE TITLE
Upgrade fails if using postgresql

### ISSUE THREAD

**Issue by roperto** [kordan/moodle-mod_surveypro#299]
The following query will fail on postgresql (my version is 9.13.14).

https://github.com/kordan/moodle-mod_surveypro/blob/master/db/upgradelib.php#L72-L77

My work around was:

`
    $sql = 'SELECT DISTINCT ON (parentid) id as childid, parentid, surveyproid
            FROM {surveypro_item}
            WHERE type = :type
                AND parentid <> :parentid
            ORDER BY parendit, surveyproid, sortindex';
`

however I am not creating a pull request because I don't know if this is MySQL compatible.

Cheers,

**Comment by kordan** [comment]
Thank you, Roperto.
I test your solution in mysql and update you here.
:-)

**Comment by kordan** [comment]
Ciao Roperto
I sent a fix to git hub for this issue.
It is in https://github.com/kordan/moodle-mod_surveypro/pull/302.
Do you have a way to test it?

**Comment by kordan** [comment]
As far as I can see there should be more errors in query for postgresql. During next days I will try to fix them. Before starting the fix I will ask you to verify they really are errors. (if you want to help).

**Comment by kordan** [comment]
fixed in #302
