### ISSUE TITLE
with extra note on getting error

### ISSUE THREAD

**Issue by martinvivek** [kordan/moodle-mod_surveypro#322]
Notice: Undefined property: surveyproformat_label_format::$extranote in Root\moodle\mod\surveypro\classes\itembase.php on line 1411

**Comment by kordan** [comment]
Thanks Martin.
I plan to look after this issue at my first available time.
I apologise but I really can not take care of it in these days.

**Comment by kordan** [comment]
I confirm the problem. Thank you.
I proposed a solution in #333.
Thanks a gain.

**Comment by kordan** [comment]
As far as I know, with #333 your issue has been fixed and closed.
Thanks a lot.
