### ISSUE TITLE
Survey Analysis Form

### ISSUE THREAD

**Issue by martinvivek** [kordan/moodle-mod_surveypro#323]
After a negative response from a group of students or a response which needs to be addressed. For that we have to make a note / justification and it should be stored on the database. 
Like that anything is available?

**Comment by martinvivek** [comment]
Like this which is in the original survey plugin. 

![image](https://cloud.githubusercontent.com/assets/7712010/23027905/c9c34c90-f48b-11e6-83f0-728b4c883b15.png)

**Comment by kordan** [comment]
Ciao Martin and thanks for the report.
I am sorry but the target of this plugin is to collect data.
Data analysis is not part of the module as collected data can be exported and reimported somewhere else for this purpose.
I am not going to add this feature.
