### ISSUE TITLE
Mexican Spanish translation of English language strings

### ISSUE THREAD

**Issue by germanvaleroelizondo** [kordan/moodle-mod_surveypro#324]
I am working hard on this. 95% made so far. But I can not upload the ZIP (We don’t support that file type). PLEASE tell me an Email address where I can send it (55kb)

**Comment by stronk7** [comment]
I think this already has been solved by #325 and your awesome translation is already there? @kordan , feel free to close if so. Thanks @germanvaleroelizondo !

**Comment by kordan** [comment]
Close as fixed in #325. Thanks, thank and thanks more German.

**Comment by kordan** [comment]
Maybe you would like to be involved (for less than a minute) in #336.
There are two more strings.
