### ISSUE TITLE
Responses View

### ISSUE THREAD

**Issue by meesir** [kordan/moodle-mod_surveypro#326]
I love the mod, but I am having an issue.  I'm attempting to have a set of questions for students and some reserved fields at the end for non-editing teachers.  I was easily able to achieve this, but the issue I'm having is that when a student enters the activity it seems they are directed to the responses tab, which they don't have access to, the same thing happens after completing submitting their form.  It doesn't break anything it just shows an error message in both cases stating the database cannot be reached.  Is there a setting I missed that would leave out the responses tab, or is there a change I can make in code to leave it out?  Any help would be appreciated.

**Comment by kordan** [comment]
Thanks meesir for your comment.
I will try to reproduce your issue and next week I will reply here.

**Comment by meesir** [comment]
Thanks a lot!

**Comment by kordan** [comment]
If I correctly remember
once you get into the module you land in view.php
In view.php the code take a decision:
if the surveypro has no elements {
    if the user can manage items (alias is like a teacher) {
        the user lands in surveypro/layout_items.php
    } else {
        the user lands in surveypro/view_cover.php
    }
} else {
	if the user just submitted an answer {
		display the thanks page and, from there, maybe resubmit
	} else {
		display the table with all previous submissions
	}
}

Do you agree on this?

**Comment by meesir** [comment]
I'm not at the computer but I do recall something along those lines.



Sent from my Samsung Galaxy smartphone.

-------- Original message --------

**Comment by kordan** [comment]
Is this issue still alive?
If so, add some more details, please.

**Comment by meesir** [comment]
I'm running Moodle 321, and users are separated into different groups, and the survey is separated by individual (so they cannot see each others results).. I have it set so the user can only submit one entry.  The problem is when a student enters the the activity they are brought straight into the responses tab, which they don't have access to.  The same happens after they save the survey (they are directed to the responses page) which shows a database permissions error in both cases.  Unfortunately I'm quite new to Moodle, so don't really know enough to find the right solution.

**Comment by kordan** [comment]
ok, maybe I understood.
You are saying: if students submitted the maximum allowed number of responses, please don't redirect them to the page to submit one more response. Is this your request?

**Comment by kordan** [comment]
mmmhhhh
I am not sure I get your problem.
I just tested a surveypro with "Maximum allowed attempts" seto to 1.
I filled it as a student and I was not redirected to the page to submit one more response.
Are you using the master branch?

**Comment by meesir** [comment]
I tried on a different machine and am not experiencing the same issue, so I assume the mistake was on my part.  Thanks a lot for taking the time to promptly try to help me with this.

**Comment by kordan** [comment]
:smile:

**Comment by meesir** [comment]
I jumped the gun, as I finished setting up the survey the error has reappeared.

**Comment by kordan** [comment]
Are you using $plugin->version = 2016102500?

**Comment by meesir** [comment]
Yes sir..

$plugin->component = 'mod_surveypro'; // Full name of the plugin (used for diagnostics).
$plugin->maturity = MATURITY_ALPHA; // MATURITY_RC.
$plugin->version = 2016102500; // The current module version (Date: YYYYMMDDXX).
$plugin->release = '1.0'; // The current release.
$plugin->requires = 2015111600; // Requires this Moodle version.
$plugin->cron = 3600; // Period for cron to check this module (in seconds).

**Comment by meesir** [comment]
The issues is not there running under 3.02, it still goes to responses tab, but shows 'Nothing to Display' instead of throwing an exception.

**Comment by kordan** [comment]
even more strange. I a tested it yesterday with last moodle head 3.3dev (Build: 20170316) and it was working fine. Tomorrow I will start one more testing session trying to apply each detail you listed here.

**Comment by meesir** [comment]
I'm about to test to see if the error occurs on 3.3.  I really appreciate your help.

**Comment by meesir** [comment]
Same issue under 3.3dev (Build: 20170316) - [http://imgur.com/a/eRK8K](url)

I wonder if there's any more info I can provide to help you replicate this?

**Comment by kordan** [comment]
Which db are you using?
I recently fixed few issues regarding postgres.
They are still not merged but you can update your copy merging them locally.
Is this your case?

**Comment by kordan** [comment]
This isi my experience:

In Firefox
Logged is as admin

Added about 50 students to the course
Auto diveded the course into 7 random groups

Created a new surveypro instance
Named it "Paul Oldham"
Set "Maximum allowed attempts" to 1
Set "Group mode" to "Separate groups"
Saved
Added a boolean element (the fastest that I always use)

In Safari
Logged is as a student
Submitted an answer
No errors at all

In Chrome
Logged is as different student
Submitted an answer
No errors at all

**Comment by meesir** [comment]
I'm using mysql, under wamp.

**Comment by kordan** [comment]
Try to add:

$CFG->debug = E_ALL | E_STRICT;
$CFG->debugdisplay = true;
$CFG->debugpageinfo = true;

to your mod330/config.php file and reproduce the error, please.

**Comment by meesir** [comment]
Error reading from database

More information about this error
Debug info: Champ: 'userid' dans where clause est ambigu
SELECT DISTINCT s.id as submissionid, s.surveyproid, s.status, s.userid, s.timecreated, s.timemodified, u.id,u.picture,u.firstname,u.lastname,u.firstnamephonetic,u.lastnamephonetic,u.middlename,u.alternatename,u.imagealt,u.email FROM m330_surveypro_submission s JOIN m330_user u ON u.id = s.userid JOIN (SELECT DISTINCT eu1_u.id
FROM m330_user eu1_u
JOIN m330_user_enrolments ej1_ue ON ej1_ue.userid = eu1_u.id
JOIN m330_enrol ej1_e ON (ej1_e.id = ej1_ue.enrolid AND ej1_e.courseid = ?)
WHERE 1 = 1 AND eu1_u.deleted = 0) eu ON eu.id = u.id JOIN m330_groups_members gm ON gm.userid = s.userid WHERE surveyproid = ? AND userid = ? AND gm.groupid = ? ORDER BY s.timecreated
[array (
0 => '2',
1 => '1',
2 => '6',
3 => 1,
)]
Error code: dmlreadexception
Stack trace:

    line 486 of \lib\dml\moodle_database.php: dml_read_exception thrown
    line 1114 of \lib\dml\mysqli_native_moodle_database.php: call to moodle_database->query_end()
    line 411 of \mod\surveypro\classes\submission.php: call to mysqli_native_moodle_database->get_recordset_sql()
    line 91 of \mod\surveypro\view.php: call to mod_surveypro_submission->display_submissions_table()

**Comment by kordan** [comment]
Cooooool.
Now I can kill it.
Give the some time, please.
Thanks.

**Comment by meesir** [comment]
Thanks so much

**Comment by kordan** [comment]
mmmhhhh my code is different from your!!
please try to include in your copy the issue #306 

cd path/to/your/mod330/mod/surveypro
git checkout master
git merge main_get_submissions_sql

This may fix the issue.

**Comment by kordan** [comment]
if you don't use git, 
download the two files listed in https://github.com/kordan/moodle-mod_surveypro/pull/306/files
and overwrite them manually.

**Comment by kordan** [comment]
There are about 26 pending issues I am waiting to integrate.
#306 is one of them.

**Comment by meesir** [comment]
That did indeed solve the problem!  Thanks!
