### ISSUE TITLE
Permissions Issue

### ISSUE THREAD

**Issue by meesir** [kordan/moodle-mod_surveypro#331]
When the ability to manage survey elements is taken away from Non-Editing teacher, the ability to Export goes away too.  Although export has it's own permission which is still enabled for Non-editing teacher.

**Comment by kordan** [comment]
Testing here. Thanks!

**Comment by kordan** [comment]
Thanks meesir.
I replicated your issue and fixed it in the frame of #328 
As soon as it will be merged, this bug will be fixed.
Thanks a lot for your contribution.

**Comment by meesir** [comment]
No problem, glad to help.
