### ISSUE TITLE
Put travis back to pass

### ISSUE THREAD

**Issue by stronk7** [kordan/moodle-mod_surveypro#403]
For some time travis has been failing completely, making it unusable. This issue is about to get it back to work and, hopefully, pass.

Maybe some of the tasks (phpunit, behat) will be moved out from travis, leaving only static (and quick) checks. Let's see...

Ciao :-)

**Comment by stronk7** [comment]
Just guessing if we can avoid some of those...

````
Multiple empty lines are not allowed
````

In feature files... they are really too much repetitive... looking...

**Comment by stronk7** [comment]
Have sent current work to merge as PR #407 . Just to have those changes already in effect. Will continue here...

**Comment by kordan** [comment]
Fixed in the frame of #407
