### ISSUE TITLE
Some answers of this response have been found as unverified

### ISSUE THREAD

**Issue by Brada65** [kordan/moodle-mod_surveypro#704]
Hello Kordan,

now, when I am already here, just one quick question. We have a lot of "in progress" responses with this explanation, can you give me some code change that will turn off any verification (not verification of fields by setting). If that is too complicated, can you explain what is causing that error message, to try to give a warning to our clients. As you maybe remember we are accepting our clients answers as they are, because they will have online meeting with Counselor where he can fix all issues. We just need that our clients submit the form with their part of questions, and to their response be "closed" (not "in progress"), and Counselor will do the rest, fixing some clients answers, and fill they own part of form (202 questions).
Thanks in advance, and just to be clear 50-something are best years in life. :)

Vladimir

**Comment by kordan** [comment]
Ciao Vladimir.
I remember you very well.
I have a a very good memory of you and your group.

About your issue, It is not clear to me your issue.
Please make a usertemplate of your surveypro.
It will results in an xml file on your local hard drive with only the fileds of your surveypro and without enrolled users and answers.
Please send me this usertemplate.
I will load it on my local moodle instance and I will try yo understad your issue following your further instructions.
Please provide me an example of the user answer resulting in the "in progress" answer and not the "closed" answer.

Kordan

**Comment by kordan** [comment]
if you want you can direct mail me to stringapiccola at gmail.com

**Comment by kordan** [comment]
As far as I know, this issue is 100% resolved. Because of this, I close it.

**Comment by kordan** [comment]
As far as I know, this issue is 100% resolved. Because of this, I close it.
