### ISSUE TITLE
readme file metions tracker.moodle.org as the location for reporting issues but github issues tracker is enabled.

### ISSUE THREAD

**Issue by danmarsden** [kordan/moodle-mod_surveypro#789]
I would suggest you update your readme and deprecate the use of the moodle tracker for tracking issues and instead rely on the github issues tracker - it allows for better tracking of pull requests matching issues, and generally provides a better experience for contributors compared with using the Moodle HQ JIRA.

This is NOT a blocker for plugins db approval.

**Comment by kordan** [comment]
Closed as #793 has been merged. Thanks Dan and Eloy!
