### ISSUE TITLE
#811 and #812 schema fix-up

### ISSUE THREAD

**Issue by ScottVerbeek** [kordan/moodle-mod_surveypro#965]
In the merge requests #811 and #812  the default values for columns `{surveyprofield_checkbox}.noanswerdefault` and `{surveyprofield_multiselect}.noanswerdefault` were changes from 2 to 0. This has not been reflected in their respective install.xml files, causing the `php admin/cli/check_database_schema.php` to fail: 

```
php admin/cli/check_database_schema.php
-------------------------------------------------------------------------------
surveyprofield_checkbox
 * column 'noanswerdefault' has default '0', expected '2' (I)
-------------------------------------------------------------------------------
surveyprofield_multiselect
 * column 'noanswerdefault' has default '0', expected '2' (I)
-------------------------------------------------------------------------------
```

**Comment by kordan** [comment]
Thanks Scott!
Your contribution is welcome.
I merge it just now.
